name: Substreams Contract Reviewer

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  process-contracts:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing to the repository
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      
      - name: Build Substreams WASM module
        run: cargo build --target wasm32-unknown-unknown --release
      
      - name: Install Substreams CLI
        run: |
          # Install Substreams CLI manually
          mkdir -p ~/.local/bin
          curl -L https://github.com/streamingfast/substreams/releases/download/v1.1.11/substreams_linux_x86_64 -o ~/.local/bin/substreams
          chmod +x ~/.local/bin/substreams
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Run Substreams
        env:
          SUBSTREAMS_API_KEY: ${{ secrets.SUBSTREAMS_API_KEY }}
        run: |
          mkdir -p output
          
          # Run Substreams directly
          ~/.local/bin/substreams run -e ${SUBSTREAMS_API_KEY}@mainnet.eth.streamingfast.io:443 \
            substreams.yaml map_contract_usage \
            --start-block 16000000 --stop-block +1000 \
            > ./output/substreams_output.json
          
          # Process the output with jq
          cat ./output/substreams_output.json | jq -c '.contracts[]' > ./output/contracts.json || echo "Failed to process output with jq"
          
          # Create a simple output file if jq fails
          if [ ! -s ./output/contracts.json ]; then
            echo '{"error": "Failed to process Substreams output"}' > ./output/contracts.json
          fi
      
      - name: Create timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M%S')"
      
      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Create results directory if it doesn't exist
          mkdir -p results
          
          # Copy output to results directory with timestamp
          cp ./output/contracts.json ./results/contracts_${{ steps.timestamp.outputs.date }}.json
          
          # Add and commit
          git add ./results/
          git commit -m "Add contract data for ${{ steps.timestamp.outputs.date }}" || echo "No changes to commit"
          # Determine which branch we're on
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$BRANCH" = "HEAD" ]; then
            # We're in detached HEAD state, use the default branch
            BRANCH="main"
          fi
          
          git push origin $BRANCH
